_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 37
                - 38
                - 41
                - 53
                - 55
                - 80
            "2":
                - 1
                - 5
                - 37
                - 38
                - 41
                - 53
                - 55
                - 80
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
backbone:
    value: ResNeXt
batch_size:
    value: 2
depth:
    value: 101
lr:
    value: 0.01
num_epochs:
    value: 12
